# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'WallJumpers' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WallJumpers
  pod 'EasyGameCenter', :git => 'https://github.com/DaRkD0G/Easy-Game-Center-Swift.git'

end
